apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: coe-netapp-san
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
spec:
  snapshotClass: coe-netapp
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block
