apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
  href: https://rhacs.coe.muc.redhat.com
  location: ApplicationMenu
  text: 'Red Hat Advanced Cluster Security for Kubernetes'