apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ExternalSecret/
- cluster-init.yaml
- console-link.yaml
- declarative-oauth.yaml
- operator.yaml
- rbac.yaml
- secured-cluster.yaml
