---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common/
  - namespace/openshift-ingress/
  # Move keepalived and ingress on master nodes only
  - cluster-scope/MachineConfig/50-remove-keepalived.yaml
  - namespace/openshift-ingress-operator/IngressController/default.yaml
  # Rollout Red Hat Root CA
  #  subject=C = US, ST = North Carolina, L = Raleigh, O = "Red Hat, Inc.", OU = Red Hat IT, CN = Red Hat IT Root CA, emailAddress = infosec@redhat.com
  #  issuer=C = US, ST = North Carolina, L = Raleigh, O = "Red Hat, Inc.", OU = Red Hat IT, CN = Red Hat IT Root CA, emailAddress = infosec@redhat.com
  - namespace/openshift-config/ConfigMap/user-ca-bundle-v1.yaml

  - namespace/openshift-config/ExternalSecret/ocp-coe-cert.yaml
  - cluster-scope/APIServer/cluster.yaml
  # This is managed by OpenShift Operator, I don't know how to solve without an
  # out of sync error.
  - namespace/openshift-controller-manager/openshift-user-ca.yaml
  # NTP Configuration
  - cluster-scope/MachineConfig/50-masters-chrony-configuration.yaml
  - cluster-scope/MachineConfig/50-workers-chrony-configuration.yaml
  # Node configuratio / labeling
  - cluster-scope/Node/inf7.yaml
  - cluster-scope/Node/inf8.yaml
  - cluster-scope/Node/ucs56.yaml

  # Scheduler
  - cluster-scope/Scheduler/cluster.yaml

  # MetalLB
  - namespace/metallb-system/MetalLB/metallb.yaml
  - namespace/metallb-system/IPAddressPool/coe-metallb.yaml

  # Networking
  #    oc api-resources  --api-group='nmstate.io'
  - ../../operators/nmstate
  - cluster-scope/NMState/nmstate.yaml
  - cluster-scope/NodeNetworkConfigurationPolicy/coe-bridge-via-enp4s0f1.yaml
  - cluster-scope/NodeNetworkConfigurationPolicy/coe-bridge-via-enp79s0f1.yaml

  # Extra.. should be an extra argo app
  - namespace/rdp-service/NetworkAttachmentDefinition/coe-bridge.yaml

  # Added project request template
  - namespace/openshift-config/Template/project-request.yaml
  - cluster-scope/Project/cluster.yaml

  # Authentication
  - namespace/openshift-config/ExternalSecret/google-client-secret.yaml
  - cluster-scope/OAuth/cluster.yaml

  # App of Apps
  - namespace/openshift-gitops/Application/app-astra-trident.yaml

components:
  - ../../components/metallb
  # - ../../components/nmstate
