apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-coe-cert
  namespace: ansible-automation-platform
spec:
  data:
  - remoteRef:
      key: coe-lab/aap-coe-cert
      property: tls.crt
    secretKey: tls.crt
  - remoteRef:
      key: coe-lab/aap-coe-cert
      property: tls.key
    secretKey: tls.key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aap-coe-cert
    template:
      type: kubernetes.io/tls
