apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stormshift-app
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'isar-baselayer-config/'
    repoURL: https://github.com/stormshift/automation.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
