apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: cluster
spec:
  trustedCA:
    name: redhat-current-it-root-cas
