apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-coe-cert
  namespace: quay-enterprise
spec:
  data:
  - remoteRef:
      key: coe-lab/quay-coe-cert
      property: tls.crt
    secretKey: crt
  - remoteRef:
      key: coe-lab/quay-coe-cert
      property: tls.key
    secretKey: key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    name: config-bundle-secret
    template:
      engineVersion: v2
      data:
        ssl.cert: "{{ .crt }}"
        ssl.key: "{{ .key }}"   
