apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-wildcard-coe
  namespace: quay-enterprise
spec:
  data:
  - remoteRef:
      key: coe-lab/wildcard-cert-coe
      property: wildcard-coe.chain.cert
    secretKey: crt
  - remoteRef:
      key: coe-lab/wildcard-cert-coe
      property: wildcard-coe.key
    secretKey: key
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redhat-vault
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    name: config-bundle-secret
    template:
      engineVersion: v2
      data:
        ssl.cert: "{{ .crt }}"
        ssl.key: "{{ .key }}"   
