apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: coe-netapp-nas
  annotations:
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - muc-a
    - muc-b
    - muc-c
  - key: topology.kubernetes.io/region
    values:
    - muc
